nextcloud/calendar_resource_management

.github/workflows/setup.yml

The room types should be taken from https://github.com/nextcloud/server/blob/d4486b8d4f698c6c93ffa6b2d1b66cf8e65f4ad8/lib/public/Calendar/Room/IRoomMetadata.php#L36

Adjust test data room types

---

lib/Command/CreateRestriction.php

Fix setting entity ID on restriction

---

.github/workflows/csfixer.yml
.github/workflows/setup.yml

Fixes https://github.com/nextcloud/groupware/issues/11

Adjust workflows to use `main`

---

lib/Command/CreateRoom.php

Fixes https://github.com/nextcloud/calendar_resource_management/issues/32

Fix creation of rooms

---

README.md

Update download instructions

---

lib/Command/ListResources.php

Fixes https://github.com/nextcloud/calendar_resource_management/issues/33
First lines of code in php. Hope it is valid. Do there have to be any changes to unittests?

Also print list of stories

---

.github/workflows/setup.yml
appinfo/info.xml

Signed-off-by: Richard Steinmetz <richard@steinmetz.cloud>

Add support for Nextcloud 25

---

.github/workflows/appstore-build-publish.yml

Signed-off-by: Richard Steinmetz <richard@steinmetz.cloud>

Create publish to appstore workflow

---

CHANGELOG.md
appinfo/info.xml

I tested it locally and it worked fine. I also started a changelog now that the app will be released on our app store.

Release v0.3.0

---

.github/workflows/setup.yml
appinfo/info.xml

Ref https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

chore(deps): Drop Nextcloud 23 support (EOL)

---

lib/AppInfo/Application.php

Migrate to new backend registrations

---

.github/workflows/setup.yml
appinfo/info.xml
composer.json
composer.lock

Ref https://github.com/nextcloud/groupware/issues/41
-  [x] Merge https://github.com/nextcloud/calendar_resource_management/pull/78

chore(deps): add PHP 8.2 support

---

.github/workflows/setup.yml
README.md
lib/Command/CreateBuilding.php
lib/Command/CreateResource.php
lib/Command/CreateRoom.php
lib/Command/CreateStory.php
lib/Command/CreateVehicle.php

Use options instead of arguments for optional parameters

---

appinfo/info.xml

feat: add support for Nextcloud 27 and drop support for 24

---

.github/workflows/lint.yml
.github/workflows/setup.yml
appinfo/info.xml

Is needed because we still support Nextcloud 25.

chore: add support for PHP 7.4

---

composer.json
composer.lock

Followup to #92 
This partially reverts a8aa43191348f1288b3f8cefb5916d5da272a962.
I forgot to fully revert all changes as they were split across 2 commits/PRs. There were no code changes regarding the drop. It was a purely cosmetic change.

feat: add support for PHP 7.4

---

.github/workflows/lint.yml

Upgrade action that works on GARM

ci: Fix XML lint

---

CHANGELOG.md
appinfo/info.xml

- Support for Nextcloud 29
- Support for PHP 8.3
- Support for Nextcloud 25
- Support for PHP 7.4

chore(release): v0.7.0

---

appinfo/info.xml

chore: reformat info.xml

---

README.md

- list a new CAVEAT, is ref #119 
- typo fix
ref #121

new CAVEAT on rooms and typo fix

---

lib/Command/CreateResource.php
lib/Command/CreateRestriction.php
lib/Command/CreateRoom.php
lib/Command/CreateVehicle.php
lib/Command/DeleteResource.php

Requires https://github.com/nextcloud/server/pull/45532
Update resources and rooms right when they are created via occ. Only works on Nextcloud 30 and newer.

feat: update resources and rooms instantly

---

.github/CODEOWNERS
renovate.json

Aligns with https://github.com/nextcloud/groupware/blob/8f662c09e9c6784ae297e0b8186eac961862b6f2/README.md

chore(github): Update code owners

---

CHANGELOG.md
appinfo/info.xml

chore(release): v0.9.0-beta.1
